### PR TITLE
First attempt at Python 3.6 support

### PR DESCRIPTION
**Pull request by pl77**
It seems to be working okay in python 3.6.

### CODE REVIEW

**Comment by pl77** [comment]
signed.

**Comment by maks-us** [comment]
@pl77 
I guess you may meed to reply exact as in instruction "I signed it!". 
I think it is automatic system.

**Comment by pl77** [comment]
It sent me back a response saying "CLAs look good, thanks!" which must be a private message if you can't see it. I didn't even think that was possible!

**Comment by mishas** [comment]
Irrelevant after merging #40

**Pull request closed without merging**
